# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Expose port 5000, as Flask runs on this port by default
EXPOSE 8000

# Define the command to run the application
# Flask's default host is 127.0.0.1, which isn't accessible from outside the container.
# We set it to 0.0.0.0 to make it accessible from other services and the host.
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]
